// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFCt3WYMSxW-xpDZN4LLXAkxWOdnmZFU',
    appId: '1:888148196242:web:476ef118a3181aab2d1f4b',
    messagingSenderId: '888148196242',
    projectId: 'baitap-a8137',
    authDomain: 'baitap-a8137.firebaseapp.com',
    storageBucket: 'baitap-a8137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhamdDhUhlJFuTGGnd9lIy8PFw7PEUVg',
    appId: '1:888148196242:android:844f0a56564764dc2d1f4b',
    messagingSenderId: '888148196242',
    projectId: 'baitap-a8137',
    storageBucket: 'baitap-a8137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALrXHqBNN8oeTmvMhi6_MTLOApsjJGTIY',
    appId: '1:888148196242:ios:43b22312b0afa1ce2d1f4b',
    messagingSenderId: '888148196242',
    projectId: 'baitap-a8137',
    storageBucket: 'baitap-a8137.firebasestorage.app',
    iosBundleId: 'com.example.baitap1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALrXHqBNN8oeTmvMhi6_MTLOApsjJGTIY',
    appId: '1:888148196242:ios:43b22312b0afa1ce2d1f4b',
    messagingSenderId: '888148196242',
    projectId: 'baitap-a8137',
    storageBucket: 'baitap-a8137.firebasestorage.app',
    iosBundleId: 'com.example.baitap1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlFCt3WYMSxW-xpDZN4LLXAkxWOdnmZFU',
    appId: '1:888148196242:web:940507c7ccea6ea52d1f4b',
    messagingSenderId: '888148196242',
    projectId: 'baitap-a8137',
    authDomain: 'baitap-a8137.firebaseapp.com',
    storageBucket: 'baitap-a8137.firebasestorage.app',
  );
}
